// Sample data and helpers

const FORMACOES = ['Arquiteto', 'Engenheiro Civil', 'Tecnólogo', 'Advogado', 'Proprietário', 'Outros'];
const NATUREZAS = ['Serviços ou Institucional', 'Residencial', 'Comercial', 'Misto', 'Industrial', 'Regularização'];

const INITIAL_TICKETS = [
  {
    id: 'PP-3C82BF5B',
    assunto: 'Dúvida sobre recuo frontal em lote de esquina',
    status: 'solucionado',
    municipe: 'Bruno Vieira',
    email: 'blv.bruno@gmail.com',
    formacao: 'Tecnólogo',
    natureza: 'Serviços ou Institucional',
    abertura: '17/04/2026 às 15:07',
    atendente: 'Arthur Saboya',
    endereco: 'R. Alvarenga, 2045 - Butantã',
    resumo: 'Município solicita esclarecimento sobre recuo frontal mínimo em lote de esquina antes de protocolar o pré-projeto.',
    mensagens: [
      { autor: 'Bruno Luiz Vieira', hora: '17/04/2026 16:24', texto: 'Bom dia. Tenho um lote de esquina e gostaria de entender qual o recuo mínimo exigido em cada frente para o pré-projeto residencial.', outgoing: false },
      { autor: 'Arthur Saboya', hora: '17/04/2026 16:47', texto: 'Olá Bruno, boa tarde. Para lote de esquina o recuo frontal mínimo é 5m em ambas as testadas. Você pode consultar o Art. 62 da LPUOS. Se quiser, anexe o croqui para confirmarmos.', outgoing: true },
      { autor: 'Bruno Luiz Vieira', hora: '17/04/2026 17:05', texto: 'Perfeito, segue croqui em anexo.', outgoing: false, anexos: [1] },
      { autor: 'Arthur Saboya', hora: '17/04/2026 17:12', texto: 'Recebido. Está correto, pode seguir com o protocolo. Qualquer dúvida adicional estamos à disposição.', outgoing: true },
      { autor: 'sistema', hora: '17/04/2026 17:13', texto: 'Chamado marcado como solucionado por Arthur Saboya.', system: true },
    ],
  },
  {
    id: 'PP-7D14A29E',
    assunto: 'Viabilidade para edifício misto – Zona Eixo',
    status: 'agendado',
    municipe: 'Camila Ferreira',
    email: 'camila.ferreira@arq.com.br',
    formacao: 'Arquiteto',
    natureza: 'Misto',
    abertura: '16/04/2026 às 10:32',
    atendente: 'Arthur Saboya',
    endereco: 'Av. Sumaré, 1122 - Perdizes',
    resumo: 'Caso complexo envolvendo ZEU — encaminhado à coordenadoria para agendamento de reunião técnica.',
    mensagens: [
      { autor: 'Camila Ferreira', hora: '16/04/2026 10:32', texto: 'Bom dia, estamos estudando a viabilidade de um edifício misto na Av. Sumaré. O lote está em ZEU — gostaria de confirmar CA, taxa de ocupação e quota ambiental.', outgoing: false },
      { autor: 'Arthur Saboya', hora: '16/04/2026 11:20', texto: 'Olá Camila. O caso envolve análise específica de ZEU com sobreposição de operação urbana. Vou encaminhar à coordenadoria para agendar uma reunião técnica presencial.', outgoing: true },
      { autor: 'sistema', hora: '16/04/2026 11:21', texto: 'Chamado enviado à coordenadoria. Aguardando agendamento.', system: true },
      { autor: 'Coordenadoria', hora: '16/04/2026 15:40', texto: 'Reunião agendada para 22/04/2026 às 14h, Sala Arthur Saboya. Envio convite por e-mail.', outgoing: true },
    ],
  },
  {
    id: 'PP-91F305A2',
    assunto: 'Regularização de edificação existente – documentação',
    status: 'aberto',
    municipe: 'José Ribeiro',
    email: 'jose.ribeiro@hotmail.com',
    formacao: 'Proprietário',
    natureza: 'Regularização',
    abertura: '17/04/2026 às 09:15',
    atendente: '—',
    endereco: 'R. das Palmeiras, 88 - Lapa',
    resumo: 'Pedido recém-aberto aguardando primeira resposta do atendente.',
    mensagens: [
      { autor: 'José Ribeiro', hora: '17/04/2026 09:15', texto: 'Boa tarde. Preciso regularizar uma edificação de 1998 e não sei quais documentos apresentar. Podem orientar?', outgoing: false },
    ],
  },
  {
    id: 'PP-4A7B1029',
    assunto: 'Uso residencial em zona mista – consulta prévia',
    status: 'solucionado',
    municipe: 'Renata Okamoto',
    email: 'renata.o@studioark.com',
    formacao: 'Arquiteto',
    natureza: 'Residencial',
    abertura: '15/04/2026 às 14:20',
    atendente: 'Arthur Saboya',
    endereco: 'R. Harmonia, 512 - Vila Madalena',
    resumo: 'Consulta simples sobre compatibilidade de uso residencial — respondida na sala.',
    mensagens: [
      { autor: 'Renata Okamoto', hora: '15/04/2026 14:20', texto: 'Gostaria de confirmar se uso residencial unifamiliar é permitido na ZM-2 da Vila Madalena.', outgoing: false },
      { autor: 'Arthur Saboya', hora: '15/04/2026 14:38', texto: 'Sim, permitido. Verificar apenas quota ambiental e áreas permeáveis conforme Art. 94.', outgoing: true },
    ],
  },
  {
    id: 'PP-BB209FE1',
    assunto: 'Pré-projeto de escola municipal – diretrizes',
    status: 'agendado',
    municipe: 'Diego Almeida',
    email: 'diego.almeida@sme.prefeitura.sp.gov.br',
    formacao: 'Engenheiro Civil',
    natureza: 'Serviços ou Institucional',
    abertura: '14/04/2026 às 08:55',
    atendente: 'Arthur Saboya',
    endereco: 'R. Dr. Rafael de Barros, 390',
    resumo: 'Projeto institucional que requer alinhamento com diretrizes urbanísticas — encaminhado para agendamento.',
    mensagens: [
      { autor: 'Diego Almeida', hora: '14/04/2026 08:55', texto: 'Estamos iniciando um pré-projeto de escola municipal de educação infantil. Gostaria de entender diretrizes específicas para equipamento institucional.', outgoing: false },
      { autor: 'Arthur Saboya', hora: '14/04/2026 09:30', texto: 'Caso institucional demanda diretrizes específicas de SEHAB e SEL. Encaminhando à coordenadoria.', outgoing: true },
      { autor: 'sistema', hora: '14/04/2026 09:31', texto: 'Chamado enviado à coordenadoria.', system: true },
    ],
  },
  {
    id: 'PP-55E7C88A',
    assunto: 'Taxa de permeabilidade em lote comercial',
    status: 'aberto',
    municipe: 'Lucas Tanaka',
    email: 'lucas.tanaka@gmail.com',
    formacao: 'Tecnólogo',
    natureza: 'Comercial',
    abertura: '17/04/2026 às 11:42',
    atendente: '—',
    endereco: 'R. Turiassu, 210 - Pompeia',
    resumo: 'Consulta sobre cálculo de taxa de permeabilidade em lote com piso drenante.',
    mensagens: [
      { autor: 'Lucas Tanaka', hora: '17/04/2026 11:42', texto: 'Posso contabilizar piso drenante como área permeável no cálculo?', outgoing: false },
    ],
  },
  {
    id: 'PP-12D3847F',
    assunto: 'Alinhamento viário e recuo obrigatório',
    status: 'solucionado',
    municipe: 'Mariana Costa',
    email: 'mariana@costaeeng.com.br',
    formacao: 'Engenheiro Civil',
    natureza: 'Residencial',
    abertura: '13/04/2026 às 16:10',
    atendente: 'Arthur Saboya',
    endereco: 'R. Clodomiro Amazonas, 1320',
    resumo: 'Pedido de análise do alinhamento oficial antes do projeto executivo.',
    mensagens: [
      { autor: 'Mariana Costa', hora: '13/04/2026 16:10', texto: 'Qual alinhamento vigente para R. Clodomiro Amazonas, altura do nº 1320?', outgoing: false },
      { autor: 'Arthur Saboya', hora: '13/04/2026 16:45', texto: 'Alinhamento conforme planta AL-4223/SIURB, disponível no SisAlinhamento. Sem recuo adicional.', outgoing: true },
    ],
  },
];

window.INITIAL_TICKETS = INITIAL_TICKETS;
window.FORMACOES = FORMACOES;
window.NATUREZAS = NATUREZAS;
